//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package maps {
	import org.flixel.*;
	
	public class MapLevel01 extends MapBase {
		//Media content declarations
		[Embed(source="MapCSV_Level01_MainLayer.txt", mimeType="application/octet-stream")] public var CSV_MainLayer:Class;
		[Embed(source="../../data/images/tiles.png")] public var Img_MainLayer:Class;

		
		public function MapLevel01() {

			_setCustomValues();

			bgColor = 0xffffffff;

			layerMainLayer = new FlxTilemap(new CSV_MainLayer, Img_MainLayer,3,0);
			layerMainLayer.x = 0;
			layerMainLayer.y = 0;
			layerMainLayer.scrollFactor.x = 1.000000;
			layerMainLayer.scrollFactor.y = 1.000000;

			allLayers = [ layerMainLayer ];


			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 320;
			boundsMaxY = 240;
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
