//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package maps {
	import org.flixel.*;
	
	public class MapPixelMap extends MapBase {
		//Media content declarations
		[Embed(source="MapCSV_PixelMap_PixelForeground.txt", mimeType="application/octet-stream")] public var CSV_PixelForeground:Class;
		[Embed(source="../../data/images/pixels.png")] public var Img_PixelForeground:Class;
		[Embed(source="MapCSV_PixelMap_PixelBackground.txt", mimeType="application/octet-stream")] public var CSV_PixelBackground:Class;
		[Embed(source="../../data/images/pixels.png")] public var Img_PixelBackground:Class;

		
		public function MapPixelMap() {

			_setCustomValues();

			bgColor = 0xffffffff;

			layerPixelForeground = new FlxTilemap(new CSV_PixelForeground, Img_PixelForeground,1,1);
			layerPixelForeground.x = 0;
			layerPixelForeground.y = 0;
			layerPixelForeground.scrollFactor.x = 1.000000;
			layerPixelForeground.scrollFactor.y = 1.000000;
			layerPixelBackground = new FlxTilemap(new CSV_PixelBackground, Img_PixelBackground,99,0);
			layerPixelBackground.x = 0;
			layerPixelBackground.y = -10;
			layerPixelBackground.scrollFactor.x = 0.500000;
			layerPixelBackground.scrollFactor.y = 0.500000;

			allLayers = [ layerPixelForeground, layerPixelBackground ];


			boundsMinX = 0;
			boundsMinY = -10;
			boundsMaxX = 480;
			boundsMaxY = 240;
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
